import './globals.scss'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import CommonHeader from '@/components/molecules/CommonHeader'
import Main from '@/components/pages/Main'
import CommonFooter from '@/components/molecules/CommmonFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CommonHeader />
          <Main>{children}</Main>
          <CommonFooter />
        </Providers>
      </body>
    </html>
  )
}
