import './globals.scss'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import CommonHeader from '@/components/molecules/CommonHeader'
import Main from '@/components/pages/Main'
import CommonFooter from '@/components/molecules/CommmonFooter'
import { NUM_OF_PAGES_LIMIT } from '@/constants'
import { getTagList } from '@/libs/microcms'
import Navigation from '@/components/molecules/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await getTagList({
    limit: NUM_OF_PAGES_LIMIT,
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CommonHeader />
          <Navigation tags={data.contents} />
          <Main>{children}</Main>
          <CommonFooter />
        </Providers>
      </body>
    </html>
  )
}
